### ISSUE TITLE
Exercice 1: Project set up

### ISSUE THREAD

**Issue by dhmmasson** [Estia-advanced-programming/issue-updater#114]
# Description 

See the [wiki][wiki_Exercice1] to read more about this first exercice. 

# tasks : 
- [ ] Updated the readme to list your team members
- [ ] Created a automated kanban project on github 
- [ ] Moved all issues from the Milestone Initiation to Git into todo
- [ ] this Issue has been closed

[wiki_Exercice1]: https://github.com/Estia-advanced-programming/pandora-public/wiki/Assignements»-Ex1
