### ISSUE TITLE
Exercice 2: Update team member information

### ISSUE THREAD

**Issue by dhmmasson** [Estia-advanced-programming/issue-updater#115]
# Description 

In this exercice all member will edit the same file on their local repository to learn about conflict resolution. 
See the [wiki][wiki_Exercice2] to read more about this first exercice. 

# Tasks

- [ ] Member1 has modified `README.md` and created a commit locally
- [ ] Member2 has modified `README.md` and created a commit locally
- [ ] Member3 has modified `README.md` and created a commit locally
- [ ] Member1 has **push**ed their commit to the remote repository
- [ ] Member2 and 3 
      - have **Pull**ed the commit from member1
      - have **Merg**ed the modification into their local repository
      - have **Commit** the change locally 
- [ ] Member2  *push* their commit to the remote repository
- [ ] Memberd3 
      - has **Pull**ed the commit from member2
      - has **Merg**ed the modification into their local repository
      - has **Commit** the change locally 
- [ ] this Issue has been closed
[wiki_Exercice2]: https://github.com/Estia-advanced-programming/pandora-public/wiki/Assignements»-Ex2
