### ISSUE TITLE
Exercice 3: Branch

### ISSUE THREAD

**Issue by dhmmasson** [Estia-advanced-programming/issue-updater#116]
# Description 

In this exercice you learn to create a branch for commiting your change before integrating it with the other. 

# Tasks 

- [ ] Member 1 has created a `dev_member1` branch locally and commited some change to it 
- [ ] Member 2 has created a `dev_member2` branch locally and commited some change to it 
- [ ] Member 3 has created a `dev_member3` branch locally and commited some change to it 
* [ ] Member 1 has pushed its branch to the remote repository 
* [ ] Member 2 has pushed its branch to the remote repository 
* [ ] Member 3 has pushed its branch to the remote repository 
- [ ] Member 1 has created a pull request and linked this issue to the pull request
- [ ] Member 2 has created a pull request and linked this issue to the pull request
- [ ] Member 3 has created a pull request and linked this issue to the pull request
* [ ] Member 2 and 3 comment on Member 1 pull request, 
    - if the change is accepted, Merge the branch into master.  
* [ ] Member 2 pull request has been discussed
    - If there are conflicts, resolve them online, 
    - if the change is accepted, Merge the branch into master.  
* [ ] Member 3 pull request has been discussed
    - If there are conflicts pull the change locally, merge them into `dev_member3`, push the new commit, and continue commenting and modifying until the pull request is accepted. 
    - if the change is accepted, Merge the branch into master.  
- [ ] The issue have been closed
[wiki_Exercice3]: https://github.com/Estia-advanced-programming/pandora-public/wiki/Assignements»-Ex3
